# frozen_string_literal: true

class CemigCode
  attr_reader :cemig_codes_physical, :cemig_codes_logical, :cemig_document_types, :cemig_movements, :cemig_modals
 
  def initialize
    init_hash
  end

  private

  def init_hash
    @cemig_movements = {
      'EXCLUSAO' => '01',
      'INCLUSAO' => '02',
      'ALTERACAO' => '03'
    }

    @cemig_modals = {'EVENTUAL' => 'E', 'PARCELADA' => 'P', 'FIXA' => 'F'}

    @cemig_codes_physical = {
      '05' => '05 - EMPRESA DEVE SER NUMERICO MAIOR QUE ZERO',
      '06' => '06 - AUTORIZACAO DE DEBITO DEVE SER IGUAL A BRANCO (HEADER)',
      '07' => '07 - AUTORIZACAO DE DEBITO DEVE SER DIFERENTE DE BRANCO',
      '08' => '08 - SUBTIPO DEVE SER IGUAL A 00,01,02,03 OU 99',
      '09' => '09 - TIPO DE DOCUMENTO DEVE SER IDEN,CPF,CGC,CTPS OU OUTR',
      '11' => '11 - DATA DE STATUS INVALIDA',
      '12' => '12 - DATA MINIMA DE INICIO DE COBRANCA INVALIDA',
      '13' => '13 - DATA DA ALTERACAO INVALIDA',
      '14' => '14 - MOVIMENTO DEVE SER IGUAL A 01,02,03',
      '15' => '15 - MODALIDADE NAO COMPATIVEL COM O GRUPO DE PARCELAS',
      '16' => '16 - MODALIDADE DE COBRANCA DEVE SER IGUAL A E,P OU F',
      '17' => '17 - DEVE SER IGUAL A 00,01,02,03,04 OU 99',
      '18' => '18 - MOVIMENTO DEVE SER IGUAL A 00 (HEADER)',
      '19' => '19 - MOVIMENTO DEVE SER IGUAL A 99 (TRAILLER)',
      '22' => '22 - TOTAL DE PARCELAS DEVE SER IGUAL A 001',
      '23' => '23 - TOTAL DE PARCELAS DEVE SER IGUAL A 999',
      '24' => '24 - DEVE SER DIFERENTE DE ZERO',
      '25' => '25 - NAO EXISTE O REGISTRO TRAILLER PARA A EMPRESA',
      '26' => '26 - NAO EXISTE O REGISTRO HEADER PARA A EMPRESA',
      '27' => '27 - TOTAL DE PARCELAS NAO CONFERE COM O VALOR INFORMADO',
      '28' => '28 - ATUALIZACAO INVALIDA. FALTA REGISTRO DE ITEM DE DEBITO (02)',
      '29' => '29 - ATUALIZACAO INVALIDA. FALTA REGISTRO DE AUTOR.DE DEBITO (01)',
      '30' => '30 - ATUALIZACAO INVALIDA.FALTA REGISTRO DE GRUPO DE PARCELAS(03)',
      '31' => '31 - TIPO DE SERVICO DEVE SER IGUAL A BRANCO (REG. AUTOR. DEB.)',
      '32' => '32 - PONTO DE CONSUMO DEVE SER NUMERICO MAIOR QUE ZERO',
      '33' => '33 - NUMERO DO DOCUMENTO DEVE SER DIFERENTE DE BRANCO',
      '34' => '34 - MOVIMENTO NAO PERMITIDO PARA ESTE TIPO DE REGISTRO',
      '35' => '35 - TIPO DE SERVICO DEVE SER NUMERICO MAIOR QUE ZERO',
      '36' => '36 - TOTAL DE PARCELAS DEVE SER NUMERICO MAIOR QUE 001',
      '37' => '37 - GRUPO DE PARCELAS DEVE SER NUMERICO MAIOR QUE ZERO',
      '38' => '38 - SOMATORIO DOS REGISTROS DEVE SER NUMERICO MAIOR QUE ZERO',
      '39' => '39 - CODIGO DO CONTRATO DEVE ESTAR PREENCHIDO',
      '40' => '40 - CONTRATO NAO PERTENCE A EMPRESA INFORMADA',
      '41' => '41 - O CONTRATO NAO ESTA ATIVO PARA A EMPRESA INFORMADA',
      '42' => '42 - NAO EXISTE A EMPRESA INFORMADA',
      '43' => '43 - SOMATORIO DOS REGISTROS NAO CONFERE COM O TOTAL INFORMADO',
      '45' => '45 - GRUPO DE PARCELAS COM MAIS DE 12 REGISTROS',
      '48' => '48 - VALOR DAS PARCELAS DEVE SER NUMERICO MAIOR QUE ZERO',
      '49' => '49 - CONTRATO NAO ESTA NO PERIODO DE VALIDADE',
      '50' => '50 - QUANTIDADE DAS PARCELAS DEVE SER NUMERICO MAIOR QUE ZERO',
      '51' => '51 - NUMERO SEQUENCIAL DAS PARCELAS INVALIDO',
      '52' => '52 - EXISTEM REGISTROS EM DUPLICATA. AUTORIZACAO DESPREZADA',
      '53' => '53 - TIPO DE SERVICO DEVE SER IGUAL A 99999 (ALT.PONTO CONSUMO)'
    }

    @cemig_codes_logical = {
      '05' => '05 - CONSUMIDOR ATUAL NAO CADASTRADO NA CEMIG',
      '06' => '06 - CONSUMIDOR NOVO NAO CADASTRADO NA CEMIG',
      '08' => '08 - TIPO DE DOCUMENTO NAO CONFERE COM O CADASTRADO NA CEMIG',
      '09' => '09 - NUMERO DO DOCUMENT0 NAO CONFERE COM O CADASTRADO NA CEMIG',
      '10' => '10 - CONTRATO NAO PERTENCE A EMPRESA INFORMADA',
      '11' => '11 - CONTRATO INVALIDO',
      '12' => '12 - NAO EXISTE A EMPRESA INFORMADA',
      '13' => '13 - NAO EXISTE O TIPO DE SERVICO INFORMADO',
      '14' => '14 - NAO EXISTE A AUTORIZACAO INFORMADA',
      '15' => '15 - PONTO DE CONSUMO INFORMADO DIFERENTE DO CADASTRADO',
      '16' => '16 - TIPO DE DOCUMENTO INFORMADO DIFERENTE DO CADASTRADO',
      '17' => '17 - NRO DO DOCUMENTO INFORMADO DIFIRENTE DO CADASTRADO',
      '18' => '18 - EXCLUSAO INVALIDA. AUTORIZACAO NAO ESTA ATIVA',
      '24' => '24 - INCLUSAO INVALIDA. JA EXISTE A AUTORIZACAO DE DEBITO',
      '25' => '25 - CONSUMIDOR NAO PERTENCE AOS RAZOES DE 01 A 18',
      '26' => '26 - NAO EXISTE ESTE TIPO DE SERVICO PARA A EMPRESA INFORMADA',
      '34' => '34 - EMPRESA INVALIDA',
      '35' => '35 - CONTRATO FORA DO PERIODO DE VALIDADE',
      '36' => '36 - TERMINO DAS PARCELAS MAIOR QUE DATA DE TERMINO DO CONTRATO',
      '38' => '38 - ALTERACAO INVALIDA. AUTORIZACAO NAO ESTA ATIVA'
    }
  end
end
